apiVersion: v1
kind: Service
metadata:
  name: mini-api
  namespace: mini-project
spec:
  selector:
    app: mini-api
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: NodePort