version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"   # Access at http://localhost:8080
    restart: unless-stopped