version: 2

sources:
  - name: olist
    database: SNOWFLAKE_LEARNING_DB
    schema: PUBLIC
    tables:
      - name: OLIST_ORDERS_DATASET
      - name: OLIST_CUSTOMERS_DATASET
      - name: OLIST_ORDER_ITEMS_DATASET